insert into student(id, firstname, lastname, email_address) values (11, 'st', '1', '1233@gmail.com')
insert into student(id, firstname, lastname, email_address) values (13, 'st', '2', '1ha@gmail.com')
insert into student(id, firstname, lastname, email_address) values (14, 'st', '3', '1he3@gmail.com')
insert into student(id, firstname, lastname, email_address) values (15, 'st', '4', '12aw3@gmail.com')
insert into student(id, firstname, lastname, email_address) values (12, 'st', '5', '123123@gmail.com')